name: Free Forex Schedule

on:
  schedule:
    - cron: '0 */2 * * 1-5'  # Runs every 2 hours, Mon-Fri (UTC)
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    env:
      CHROME_PATH: /usr/bin/google-chrome
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests selenium pytz

    - name: Set up Chrome
      uses: browser-actions/setup-chrome@latest

    - name: Run Forex Signal Bot
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        echo "🚀 Running Forex Signal Bot at $(date -u)"
        python3 Free_Forex_Signal.py
