name: Forex Signal Bot

on:
  schedule:
    - cron: '0 */2 * * 1-5'  # Every 2 hours, Mon-Fri
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests selenium pytz

    - name: Set up Chrome
      uses: browser-actions/setup-chrome@latest
      with:
        chrome-version: 'stable'

    - name: Verify Chrome installation
      run: |
        google-chrome --version
        chromedriver --version

    - name: Run Forex Signal Bot
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        echo "🚀 Running at $(date -u)"
        python3 Free_Forex_Signal.py
        
        # Capture debug information
        echo "=== SCRAPER DEBUG ==="
        ls -lah
        echo "--- PAGE CONTENT ---"
        cat page_content.txt || echo "No page content"
        echo "--- CHROMEDRIVER LOG ---"
        cat chromedriver.log || echo "No chromedriver log"

    - name: Upload debug files
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: debug-files
        path: |
          page_content.txt
          chromedriver.log
          latest_signals.json
