name: Forex Signal Bot

on:
  schedule:
    - cron: '0 */2 * * 1-5'  # Every 2 hours, Mon-Fri (00:00, 02:00, ..., 22:00 UTC)
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests selenium pytz

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver

    - name: Run Forex Signal Bot
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        echo "🚀 Running at $(date -u)"
        python3 Free_Forex_Signal.py

    - name: Upload debug files
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: debug-files
        path: latest_signals.json
