name: Forex Signals Scraper

on:
  schedule:
    # Run every 2 hours from Monday to Friday (UTC time)
    - cron: '0 */2 * * 1-5'
 # Run every 1 hour from Monday to Friday (UTC time)
    - cron: '0 * * * 1-5'
  workflow_dispatch:  # Allow manual triggers

jobs:
  scrape-and-send:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium requests pytz python-dotenv
        
    - name: Install Chrome
      uses: browser-actions/setup-chrome@latest

    - name: Run Forex Signal Scraper
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python Free_Forex_Signal.py
