# .github/workflows/forex-signal-hourly.yml
name: Forex Signal Hourly
on:
  schedule:
    - cron: '0 3-23 * * 1'
    - cron: '0 * * * 2-4'
    - cron: '0 0-11 * * 5'
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    env:
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}
      OANDA_TOKEN:         ${{ secrets.OANDA_TOKEN }}
      OANDA_ACCOUNT_ID:    ${{ secrets.OANDA_ACCOUNT_ID }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install TA‑Lib C Library
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential autoconf automake libtool wget
        wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
        tar -xzf ta-lib-0.4.0-src.tar.gz
        cd ta-lib
        ./configure --prefix=/usr
        make
        sudo make install
        sudo ldconfig

    - name: Install Python deps
      run: |
        python -m pip install --upgrade pip wheel
        export TA_INCLUDE_PATH=/usr/include
        export TA_LIBRARY_PATH=/usr/lib
        pip install ta-lib
        pip install -r requirements.txt

    - name: Run Scanner
      run: python scanner.py
